staging:
  database:
    uri: "mongodb://localhost:27117"
    dbName: "school_staging"
  jwt:
    secret: "staging_super_secret_key_1234567890_change_me_in_real_life"
    expiresIn: "24h"
  ollama:
    endpoint: "http://localhost:11434"
    model: "qwen2.5:1.5b"
  security:
    allowDestructiveCommands: true # e.g. allowing seed resets
    enableFirewall: true
    enableRebac: true
    enableSanitation: true

production:
  database:
    uri: "mongodb://localhost:27118"
    dbName: "school_production"
  jwt:
    secret: "production_ultra_secure_secret_key_9876543210_never_expose"
    expiresIn: "2h"
  ollama:
    endpoint: "http://localhost:11434"
    model: "qwen2.5:1.5b"
  security:
    allowDestructiveCommands: false # strict block in production
    enableFirewall: true
    enableRebac: true
    enableSanitation: true
